Account for check_output returning bytes in Python 3.8.
Fixes errors like:

Traceback (most recent call last):
  File "/home/w/.local/bin/giza", line 8, in <module>
    sys.exit(main())
  File "/home/w/.local/lib/python3.8/site-packages/giza/cmdline.py", line 162, in main
    argh.dispatch(parser, namespace=args)
  File "/home/w/.local/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/w/.local/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/w/.local/lib/python3.8/site-packages/argh/dispatching.py", line 231, in _call
    result = function(namespace_obj)
  File "/home/w/.local/lib/python3.8/site-packages/giza/operations/make.py", line 140, in main
    run_make_operations(targets, conf)
  File "/home/w/.local/lib/python3.8/site-packages/giza/operations/make.py", line 235, in run_make_operations
    sphinx_publication(conf, app)
  File "/home/w/.local/lib/python3.8/site-packages/giza/operations/sphinx_cmds.py", line 103, in sphinx_publication
    sphinx_content_preperation(app, conf)
  File "/home/w/.local/lib/python3.8/site-packages/giza/operations/sphinx_cmds.py", line 197, in sphinx_content_preperation
    dependency_refresh_app.extend_queue(refresh_dependency_tasks(build_config))
  File "/home/w/.local/lib/python3.8/site-packages/giza/content/dependencies.py", line 132, in refresh_dependency_tasks
    refresh_deps(conf)
  File "/home/w/.local/lib/python3.8/site-packages/giza/content/dependencies.py", line 106, in refresh_deps
    graph = include_files(conf=conf)
  File "/home/w/.local/lib/python3.8/site-packages/giza/includes.py", line 44, in include_files
    for d in grep.split('\n')]
TypeError: a bytes-like object is required, not 'str'